package com.workshop.crediaexampledomaindata;

import com.workshop.CompanyData;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SEPATransfers extends CompanyData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "SEPATRANSFERS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SEPATRANSFERS_ID_GENERATOR", sequenceName = "SEPATRANSFERS_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Destiny Account Number")
	private java.lang.String destinyAccountNumber;

	@org.kie.api.definition.type.Label("Destiny Full Name")
	private java.lang.String destinyFullName;

	@org.kie.api.definition.type.Label("Amount")
	private java.lang.Float amount;

	public SEPATransfers() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getDestinyAccountNumber() {
		return this.destinyAccountNumber;
	}

	public void setDestinyAccountNumber(java.lang.String destinyAccountNumber) {
		this.destinyAccountNumber = destinyAccountNumber;
	}

	public java.lang.String getDestinyFullName() {
		return this.destinyFullName;
	}

	public void setDestinyFullName(java.lang.String destinyFullName) {
		this.destinyFullName = destinyFullName;
	}

	public java.lang.Float getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Float amount) {
		this.amount = amount;
	}

	public SEPATransfers(java.lang.Long id,
			java.lang.String destinyAccountNumber,
			java.lang.String destinyFullName, java.lang.Float amount) {
		this.id = id;
		this.destinyAccountNumber = destinyAccountNumber;
		this.destinyFullName = destinyFullName;
		this.amount = amount;
	}

}